[package]
name = "piggy"
version = "0.1.0"
edition = "2021"

[lib]
crate_type = ["cdylib", "rlib"]

[dependencies]
engine_sdk = { path = "../engine_sdk" }
serde = { version = "1.0", features = ["derive"]}
bincode = "1.3.3"
